name: 05 -2- fillters activity types

on: 
    pull_request:
      types:
        - closed
      branches:
        - main

jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - run: echo "Running whenever PR is closed"
